### PR TITLE
[VSC-1841] Patch extension activation logic

### LINKED ISSUE #1756: Unable to activate the extension in projects with custom setup (VSC-1841)
### OS

Linux

### Operating System version

Ubuntu 24.04

### Visual Studio Code version

1.107.1

### ESP-IDF version

5.5.2

### Python version

3.12.3

### Doctor command output

Not applicable

### Extension

_No response_

### Description

Since commit https://github.com/espressif/vscode-esp-idf-extension/commit/3bd2221a4b3836e5e1d750b9cfb6227f12b6cdc5 this extension will not activate anymore if the root CMakeLists.txt file does not contain the line ```include($ENV{IDF_PATH}/tools/cmake/project.cmake)```.

Projects having a more advanced setup may not use the root cmake file this way will not be able to use the extension anymore.

I suggest having some other method as well to tell the extension this is an ESP-IDF project. Maybe something in `.vscode/settings.json`?

### Debug Message

Not applicable

### Other Steps to Reproduce

_No response_

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [x] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

### PR DESCRIPTION
**Pull request by radurentea**
## Description

Adds `idf.extensionActivationMode` setting (`detect` / `always` / `never`) to provide explicit control over ESP-IDF extension activation, addressing projects with custom CMake configurations that don’t use the standard ESP-IDF `project.cmake` include.

The activation logic follows a priority hierarchy:
1. **Workspace/global mode**
   - `always` = activate immediately (skip CMake detection)
   - `never` = don’t activate (no prompt)
   - `detect` = continue with folder checks / CMake fallback
2. **Folder-level mode** (multi-root)
   - Any folder set to `always` activates the extension (“always wins”)
   - If all folders are `never`, don’t activate (no prompt)
   - Otherwise continue
3. **CMakeLists.txt detection** (fallback for backward compatibility / `detect` mode)
4. **User prompt** (“Activate Anyway” dialog) when no standard ESP-IDF project is detected and mode is effectively `detect`

Fixes #1756

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update _(completed: `docs_espressif/en/extension-activation.rst` and Chinese version)_

### Test 1: Force enable for custom project

1. Open a project without standard ESP-IDF CMakeLists.txt
2. Add to workspace settings: `"idf.extensionActivationMode": "always"`
3. Reload VS Code window

- **Expected behaviour**: Extension activates without CMake detection
- **Expected output**: ESP-IDF commands available in command palette

### Test 2: Explicit disable

1. Open standard ESP-IDF project with include($ENV{IDF_PATH}/tools/cmake/project.cmake) in CMakeLists.txt
2. Add to workspace settings: `"idf.extensionActivationMode": "never"`
3. Reload VS Code window

- **Expected behaviour**: Extension does NOT activate, no prompt shown
- **Expected output**: No ESP-IDF commands available

### Test 3: Explicit disable

1. Open standard ESP-IDF project with include($ENV{IDF_PATH}/tools/cmake/project.cmake) in CMakeLists.txt
4. Add to workspace settings: `"idf.extensionActivationMode": "detect"`
5. Reload VS Code window

- **Expected behaviour**: Extension does activate
- **Expected output**: ESP-IDF commands available

### Test 4: Multi-root workspace with mixed projects

1. Create workspace with 2 folders: one ESP-IDF, one non-ESP-IDF
2. Set `"idf.extensionActivationMode": "always"` in ESP-IDF folder settings
4. Set `"idf.extensionActivationMode": "never"` in non-ESP-IDF folder settings
6. Reload VS Code window

- **Expected behaviour**: Extension activates (“always wins”)
- **Expected output**: ESP-IDF commands available

### Test 5: Standard project (backward compatibility)

1. Open standard ESP-IDF project with `include($ENV{IDF_PATH}/tools/cmake/project.cmake)` in CMakeLists.txt
2. Don’t set `idf.extensionActivationMode` (leave default)
3. Reload VS Code window

- **Expected behaviour**: Extension activates via CMake detection
- **Expected output**: ESP-IDF commands available, no prompt shown

### Test 6: No ESP-IDF project detected

1. Open non-ESP-IDF project
2. Set `"idf.extensionActivationMode": "detect"` (or leave default)
3. Reload VS Code window

- **Expected behaviour**: Prompt appears: “No standard ESP-IDF project was found…”
- **Expected output**: User can choose “Activate Anyway” or dismiss

## How has this been tested?

As described above

**Test Configuration**:
* ESP-IDF Version: Doesn’t matter
* OS (Windows, Linux and macOS): Doesn’t matter

## Checklist
- [ ] PR Self Reviewed
- [x] Applied Code formatting
- [x] Added Documentation
- [ ] Added Unit Test
- [ ] Verified on all platforms - Windows,Linux and macOS

## Summary by CodeRabbit

* **New Features**
  * Added idf.extensionActivationMode setting ("detect" default, "always", "never") that influences when the extension initializes and can prompt to activate if no project is detected.

* **Documentation**
  * Added comprehensive activation docs in English and Chinese, updated indexes and FAQ anchors with examples and troubleshooting.

* **Localization**
  * Added UI strings for the new activation setting in Spanish, Portuguese, Russian, and Chinese.

* **Templates**
  * Project template now recommends activating the extension by default ("always").

### CODE REVIEW

File: src/extension.ts [hunk 1]
```diff
@@ -260,56 +260,117 @@ export async function activate(context: vscode.ExtensionContext) {
...
-            hasValidIdfProject = true;
-            break; // Found a valid project, activate immediately
-          }
-        } catch (error) {
-          Logger.error(
-            `Error reading root CMakeLists.txt for activation check in ${workspaceFolder.name}.`,
-            error,
-            "extension activate checkCMakeContent"
+      if (workspaceValue === "always") {
+        // Activate immediately; skip folder checks and CMake detection.
```
Comment (kolipakakondal) [inline src/extension.ts:285]: Add a log for tracing purpose on why the extension is activated.

idf.extensionActivationMode=always (workspace/global)

File: src/extension.ts [hunk 2]
```diff
@@ -260,56 +260,117 @@ export async function activate(context: vscode.ExtensionContext) {
...
+          const folderValue = normalizeActivationMode(
+            idfConf.readParameter(activationModeConfigKey, folder.uri)
           );
+          if (folderValue === "always") {
+            hasAnyFolderAlways = true;
+            allFoldersNever = false;
+            break;
+          }
+          if (folderValue !== "never") {
+            allFoldersNever = false;
```
Comment (kolipakakondal) [inline src/extension.ts:311]: Here as well

if (hasAnyFolderAlways) {
          // log 
        }

**Review by Fabricio-ESP — APPROVED** [review]
Thanks for the change
