### PR TITLE
Fix space in path in python issues (VSC-283)

### LINKED ISSUE #79: SPACE in Path to Python on Windows prevents completion of the Onboarding wizzard (VSC-282)
**Describe the bug**
Unable to complete IDF Onboarding config steps. Everything checks in OK, except the last step when verifying Python requirements..
##################################################
Verify Python packages requirements
Command failed: C:\Users\STUPID USER\.espressif\python_env\idf4.0_py3.8_env\Scripts\python.exe c:\esp\esp-idf\tools\check_python_dependencies.py -r c:\esp\esp-idf\requirements.txt
'C:\Users\STUPID' is not recognized as an internal or external command,
operable program or batch file.
###################################################
The above runs OK at command prompt with quotation marks around "C:\Users\STUPID USER\.espressif\python_env\idf4.0_py3.8_env\Scripts\python.exe"

**To Reproduce**
Follow the Onboarding Wizzard config steps on Windows 10 with a SPACE in full path to python.exe

**Expected behavior**
All requirements satisfied and configuration saved.

**Environment:**
- OS Name & Version: Windows 10
- VSCode Version: 1.43.2
- ESP-IDF Version: 4.0
- Python Version: 3.8.2

### PR DESCRIPTION
**Pull request by brianignacio5**
Fix #79 

Need to quote python binary in those places where virtual environment is created and dependencies are being installed.

Use current idfPath and toolsPath from onboarding in python packages install.

### CODE REVIEW

File: src/onboarding/pythonReqsManager.ts [hunk 1]
```diff
@@ -72,7 +72,7 @@ export async function checkPythonRequirements(
   process.env.IDF_PATH = espIdfPath || process.env.IDF_PATH;
   await utils
     .execChildProcess(
-      `${pythonBin} ${reqFilePath} -r ${requirements}`,
+      `"${pythonBin}" ${reqFilePath} -r ${requirements}`,
```
Comment (SoumeshBanerjee) [inline src/onboarding/pythonReqsManager.ts:75]: `reqFilePath ` and `requirements ` might also contain spaces, if so, what will happen then?

File: src/extension.ts [hunk 2]
```diff
@@ -1277,7 +1278,7 @@ function createIdfTerminal() {
     const espIdfTerminal = vscode.window.createTerminal({
       name: "ESP-IDF Terminal",
       env: modifiedEnv,
-      cwd: workspaceRoot.fsPath,
+      cwd: workspaceRoot.fsPath || modifiedEnv.IDF_PATH || process.cwd(),
```
Comment (SoumeshBanerjee) [inline src/extension.ts:1281]: Why `|| modifiedEnv.IDF_PATH || process.cwd(),`, since we need to launch the monitor in the IDF_Project root, which is `workspaceRoot.fsPath`

File: src/onboarding/pythonReqsManager.ts [hunk 3]
```diff
@@ -86,7 +86,7 @@ export async function checkPythonRequirements(
       });
       await utils
         .execChildProcess(
-          `${pythonBin} ${reqFilePath} -r ${debugAdapterRequirements}`,
+          `"${pythonBin}" ${reqFilePath} -r ${debugAdapterRequirements}`,
```
Comment (SoumeshBanerjee) [inline src/onboarding/pythonReqsManager.ts:89]: Same here

File: src/extension.ts (hunk 2 above)
Comment (brianignacio5) [reply src/extension.ts:1281]: Fallback when launching a terminal with no opened folder.
