### PR TITLE
use sdkconfig file path from project description json

### LINKED ISSUE #1746: sdkconfig not found when using cmake variables (VSC-1832)
When building the project a popup appears and the process gets stopped with the message "sdkconfig file doesn't exists or can't be read".

### Explanation

This happens because in https://github.com/espressif/vscode-esp-idf-extension/blob/master/src/utils.ts#L477 the CMakeLists.txt is parsed to find the SDKCONFIG variable. I am using if statements to select between multiple targets so for my project this approach will not work.

Here is a snippet from my CMakeLists.txt:
Image

I would like it if you could add a fallback. It is already possible to configure the sdkconfig file path in the ESP-IDF project configuration:

Image

### Preferred solution

Please make it so that the function getSDKConfigFilePath uses this configuration setting either as a fallback when the cmake method fails or explicitly.

### Debug Message

sdkconfig file doesn't exists or can't be read

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [x] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

### PR DESCRIPTION
**Pull request by brianignacio5**
## Description

SDK config file resolution should always come from project_description.json if available. Fallback are idf.sdkconfigFilePath (default is empty string) and after is `<project root directory>/sdkconfig`. Remove any CMakeLists.txt parsing logic.

Fixes #1746

## Copilot summary

This pull request refactors how the SDK config file path is determined and accessed across the codebase. The main change is moving the `getSDKConfigFilePath` function from `utils.ts` to `workspaceConfig.ts` and updating its implementation to use information from the project's `project_description.json` when available. This improves accuracy and maintainability. All imports and usages of `getSDKConfigFilePath` have been updated accordingly. Additionally, the project description parsing logic is now centralized and more robust.

**Refactoring and centralization of SDK config file logic:**

* Moved and refactored `getSDKConfigFilePath` from `utils.ts` to `workspaceConfig.ts`, updating its logic to first attempt to read the config file path from `project_description.json` for improved accuracy. The function now returns `undefined` if the workspace path is not provided or if errors occur. [[1]](diffhunk://#diff-39b2554fd18da165b59a6351b1aafff3714e2a80c1435f2de9706355b4d32351L465-L507) [[2]](diffhunk://#diff-fb0bb13db334c106cb7a2b1b9f36dc4af698b68be775f5ef79d2c03d2d25b862L49-R181)
* Updated all imports and usages of `getSDKConfigFilePath` throughout the codebase to import from `workspaceConfig.ts` instead of `utils.ts`. This affects files such as `buildTask.ts`, `confServerProcess.ts`, `task.ts`, and `extension.ts`. [[1]](diffhunk://#diff-6624d580b86018dd10e272455fb29016ba0dc87bb4a7ab175419f7466ac6daa8L26-R31) [[2]](diffhunk://#diff-0da02128563b2f2fca0f433f5c254fd5922bcb68094e714a9accf7c3a901a7c6L28) [[3]](diffhunk://#diff-0da02128563b2f2fca0f433f5c254fd5922bcb68094e714a9accf7c3a901a7c6R36) [[4]](diffhunk://#diff-f18b1f556fa4a4c6dea7cf7d7ab8cc3fa4a4f6c64126230b7d4c54c18a41aa4eL30-R34) [[5]](diffhunk://#diff-04bba6a35cad1c794cbbe677678a51de13441b7a6ee8592b7b50be1f05c6f626R43) [[6]](diffhunk://#diff-04bba6a35cad1c794cbbe677678a51de13441b7a6ee8592b7b50be1f05c6f626L3567-R3568) [[7]](diffhunk://#diff-04bba6a35cad1c794cbbe677678a51de13441b7a6ee8592b7b50be1f05c6f626L4346-R4345) [[8]](diffhunk://#diff-39b2554fd18da165b59a6351b1aafff3714e2a80c1435f2de9706355b4d32351L39-R39)

**Project description handling improvements:**

* Introduced `getProjectDescriptionJson` in `workspaceConfig.ts`, which parses and returns a strongly-typed project description object from `project_description.json`. This centralizes and standardizes access to project metadata.
* Updated `getProjectName` in `workspaceConfig.ts` to use the new `getProjectDescriptionJson` function, improving reliability and error handling when retrieving the project name.
* Added an `IProjectDescription` interface to define the structure of the project description object, improving type safety and code clarity.

## Type of change

Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)

## Steps to test this pull request

Provide a list of steps to test changes in this PR and required output

1. Click on "Build your project" or "SDK Configuration editor" and it should work as usual.
2. Use a project that defines SDKCONFIG in CMakelists.txt like [multi_config esp-idf example](https://github.com/espressif/esp-idf/tree/master/examples/build_system/cmake/multi_config) the results should be the same.
3. Observe results.

- Expected behaviour:

SDK config file path is always correct for extension commands.

- Expected output:

Build, SDK Config editor and reconfigure tasks should work as normal.

## How has this been tested?

Manual testing following steps above.

**Test Configuration**:
* ESP-IDF Version: 6.0.0
* OS (Windows,Linux and macOS): macOS

## Checklist
- [ ] PR Self Reviewed
- [ ] Applied Code formatting
- [ ] Added Documentation
- [ ] Added Unit Test
- [ ] Verified on all platforms - Windows,Linux and macOS

## Summary by CodeRabbit

* **Refactor**
  * Centralized project/SDK config and artifact path resolution so tools consistently locate sdkconfig, ELF and map files.
  * Safer workspace handling and consolidated project description parsing for name/map/ELF discovery.

* **Bug Fixes**
  * Only add SDKCONFIG compiler arg when a valid config file exists; avoid duplicates and two-token forms.
  * Improved error handling and early returns when ELF/config/python resolution fail; better error messages.
  * GUI/menuconfig flows now guard missing processes, await value loads, and avoid crashes on panel/state changes.

### CODE REVIEW

File: src/espIdf/menuconfig/confServerProcess.ts [hunk 1]
```diff
@@ -235,14 +265,22 @@ export class ConfserverProcess {
...
+      currWorkspace
+    ) as string;
+    const hasSdkconfigArg = reconfigureArgs.some(
+      (arg, index) =>
+        arg.startsWith("-DSDKCONFIG=") ||
+        (arg === "-D" && reconfigureArgs[index + 1]?.startsWith("SDKCONFIG="))
+    );
+
+    if (sdkconfigFile && !hasSdkconfigArg) {
+      reconfigureArgs.push(`-DSDKCONFIG='${sdkconfigFile}'`);
```
[the remark this answers is not in the document]
Comment (brianignacio5) [reply src/espIdf/menuconfig/confServerProcess.ts:285]: That is the desired behavior. Only set the sdkconfig argument when a custom sdkconfig file path is given. Otherwise rely on whatever the build system would use.

File: src/workspaceConfig.ts [hunk 2]
```diff
@@ -46,41 +94,187 @@ export function updateIdfComponentsTree(workspaceFolder: vscode.Uri) {
...
+    Logger.error(
+      `Error reading project description JSON from ${buildDirPath}`,
+      error as Error,
+      "workspaceConfig getProjectDescriptionJson"
+    );
+    return undefined;
+  }
+}
+
+export async function getSDKConfigFilePath(
```
Comment (radurentea) [inline src/workspaceConfig.ts:222]: I think we should use JS Doc for this fn since we use it in multiple places throughout the extension. Something similar to:

```
 * Resolves the sdkconfig file path for a workspace.
 
 * Lookup order:
 * 1) `configFile` from `project_description.json` (if present and exists),
 * 2) `idf.sdkconfigFilePath` setting for the workspace,
 * 3) `${workspace}/sdkconfig` fallback.
```

File: src/workspaceConfig.ts [hunk 3]
```diff
@@ -46,41 +94,187 @@ export function updateIdfComponentsTree(workspaceFolder: vscode.Uri) {
   idfDataProvider.refresh(workspaceFolder);
 }
 
-export function getProjectName(buildDir: string): Promise<string> {
-  const projDescJsonPath = path.join(buildDir, "project_description.json");
-  return new Promise((resolve, reject) => {
-    try {
-      if (!utils.fileExists(projDescJsonPath)) {
-        return reject(new Error(`${projDescJsonPath} doesn't exist.`));
+export async function getProjectDescriptionJson(
```
Comment (radurentea) [inline src/workspaceConfig.ts:105]: Maybe we could add a JSDoc comment here? Even if the function is only used locally, it might still help with clarity and future maintenance.

Something like:
```
/**
 * Reads and maps `${idf.buildPath}/project_description.json` into a typed object.
 *
 * Returns `undefined` when the build directory or file is missing, content is invalid,
 * or parsing/reading fails.
 */
```

File: src/workspaceConfig.ts [hunk 4]
```diff
@@ -46,41 +94,187 @@ export function updateIdfComponentsTree(workspaceFolder: vscode.Uri) {
...
+    const errMsg =
+      error && typeof error === "object" && "message" in error
+        ? (error as Error).message
+        : String(error);
+    Logger.error(errMsg, error as Error, "workspaceConfig getSdkconfigPath");
+    return path.join(workspacePath.fsPath, "sdkconfig");
+  }
+}
+
+export async function getProjectName(
```
Comment (radurentea) [inline src/workspaceConfig.ts:259]: Same here, JSDoc could help:
```
/**
 * Returns `projectName` from `project_description.json`.
 * Throws if the file cannot be read or `projectName` is missing.
 */
```

File: src/workspaceConfig.ts [hunk 5]
```diff
@@ -46,41 +94,187 @@ export function updateIdfComponentsTree(workspaceFolder: vscode.Uri) {
...
+  workspacePath: vscode.Uri
+): Promise<string> {
+  const projectDescription = await getProjectDescriptionJson(workspacePath);
+  if (projectDescription && projectDescription.projectName) {
+    return projectDescription.projectName;
+  }
+  throw new Error("Failed to get project name from project description.");
+}
+
+export async function getProjectElfFilePath(
```
Comment (radurentea) [inline src/workspaceConfig.ts:275]: JSDoc could help, this fn is used in a lot of other places outside of this file.

```
/**
 * Returns the full path to the app ELF file using `idf.buildPath` and `appElf`
 * from `project_description.json`.
 * Throws if `project_description.json` is missing `appElf` or `idf.buildPath` is missing.
 */
```

File: src/workspaceConfig.ts [hunk 6]
```diff
@@ -46,41 +94,187 @@ export function updateIdfComponentsTree(workspaceFolder: vscode.Uri) {
...
+    }
+    const elfFilePath = path.join(buildDirPath, projectDescription.appElf);
+    return elfFilePath;
+  }
+  throw new Error(
+    "Failed to get project ELF file name from project description."
+  );
+}
+
+export async function getProjectMapFilePath(
```
Comment (radurentea) [inline src/workspaceConfig.ts:302]: JSDoc could help here also since fn is used outside of this file.
```
/**
 * Returns the full path to `${projectName}.map` using `idf.buildPath`.
 * Throws if `projectName` cannot be read from `project_description.json`
 * or if `idf.buildPath` is missing.
 */
```

File: src/workspaceConfig.ts [hunk 7]
```diff
@@ -46,41 +94,187 @@ export function updateIdfComponentsTree(workspaceFolder: vscode.Uri) {
...
+  }
+  const buildDirPath = readParameter("idf.buildPath", workspacePath) as string;
+  if (!buildDirPath) {
+    throw new Error("Failed to get build directory path for MAP file path.");
+  }
+  const mapFilePath = path.join(buildDirPath, `${projectName}.map`);
+  return mapFilePath;
 }
 
 export async function getIdfTargetFromSdkconfig(
```
Comment (radurentea) [inline src/workspaceConfig.ts:325]: Not related to this PR directly, but maybe we could add a JSDoc here as well for consistency? This fn is used quite a lot outside of this file.
```
/**
 * Returns the IDF target from `sdkconfig` (`CONFIG_IDF_TARGET`) if available.
 * If not available, uses `idf.customExtraVars.IDF_TARGET`; if still missing, returns `"esp32"`.
 * Updates `statusItem.text` with the resolved IDF target when `statusItem` is provided.
 */
```

File: src/espIdf/tracing/appTracePanel.ts [hunk 8]
```diff
@@ -243,7 +243,7 @@ export class AppTracePanel {
         const fn = async (address) => {
           const addr2line = new Addr2Line(
             workspaceRoot,
-            await getElfFilePath(workspaceRoot),
+            await getProjectElfFilePath(workspaceRoot),
             address
```
[the remark this answers is not in the document]
Comment (radurentea) [reply src/espIdf/tracing/appTracePanel.ts:261]: I agree that `resolveAddresses` can throw (e.g. when no workspace is open) and that error is not currently caught. Also, async failures from `Promise.all(promises)` are unhandled right now because there is no `.catch(...)`.

**Review by radurentea — APPROVED** [review]
Nice work, LGTM.

I left some comments in regards to adding some JSDoc, I think it will benefit us long term.

I've also left a comment related to an uncatched error, but I think the scenario in which that could happen is extremely rare.

**Review by AndriiFilippov — APPROVED** [review]
LGTM 👍
