### PR TITLE
Fix the registerIDFCommand by returning the closure's result (VSC-382)

### LINKED ISSUE #141: Debug Tasks are completely non-functional (VSC-381)
**Pre Bug Report Checklist**
Before reporting any bug please make sure of these points.

- [ check] Make sure you have searched for existing bugs and features request before you post an issue.
- [ check] This is a bug report for the ESP-IDF Visual Studio Code extension and **not** an ESP-IDF bug report.
- [ check] I've read the docs and found no information that could have helped solving the issue.

After installing vscode, esp-idf prerequisites, and properly configuring esp-idf, and creating blink project from examples, I attempted to use the debug functionality.

I had to set up the necessary board configuration and add the interface and board .cfg references.

Note - Build, flash, clean, and monitor all work, when run either as tasks or from the bottom bar.

Starting openOCD works from the bottom bar, but when running it from the tasks selected from the command palette, nothing happens. Absolutely nothing. Trying to debug from the sidebar by running the 'launch.json' task also does nothing. Running the 'adapter' task also does nothing.

Here are my configuration files:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "espidf",
            "name": "Launch",
            "request": "launch",
            "env": {
                    "PYTHONPATH": "${command:espIdf.getExtensionPath}/esp_debug_adapter/debug_adapter"
                }
        }
    ]
}
```

```
{
  "C_Cpp.clang_format_style": "Visual Studio",
  "editor.formatOnSave": false,
  "[cpp]": {
    "editor.quickSuggestions": true
  },
  "[c]": {
    "editor.quickSuggestions": true
  },
  "C_Cpp.intelliSenseEngineFallback": "Enabled",
  "idf.adapterTargetName": "esp32",
  "idf.port": "/dev/ttyUSB0",
  "idf.openOcdConfigs": [
    "interface/ftdi/esp32_devkitj_v1.cfg",
    "board/esp32-wrover.cfg"
  ]
}
```

```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Build - Build project",
            "type": "shell",
            "command": "${config:idf.pythonBinPath} ${config:idf.espIdfPath}/tools/idf.py build",
            "windows": {
                "command": "${config:idf.pythonBinPathWin} ${config:idf.espIdfPathWin}\\tools\\idf.py build"
            },
            "options": {
                "env": {
                    "PATH": "${config:idf.customExtraPaths}"
                }
            },
            "problemMatcher": [
                {
                    "owner": "cpp",
                    "fileLocation": ["relative", "${workspaceFolder}"],
                    "pattern": {
                        "regexp": "^\\.\\.(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
                        "file": 1,
                        "line": 2,
                        "column": 3,
                        "severity": 4,
                        "message": 5
                    }
                },
                {
                    "owner": "cpp",
                    "fileLocation": "absolute",
                    "pattern": {
                        "regexp": "^[^\\.](.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
                        "file": 1,
                        "line": 2,
                        "column": 3,
                        "severity": 4,
                        "message": 5
                    }
                }
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        },
        {
            "label": "Set ESP-IDF Target",
            "type": "shell",
            "command": "${command:espIdf.setTarget}",
            "problemMatcher": {
                "owner": "cpp",
                "fileLocation": "absolute",
                "pattern": {
                    "regexp": "^(.*):(//d+):(//d+)://s+(warning|error)://s+(.*)$",
                    "file": 1,
                    "line": 2,
                    "column": 3,
                    "severity": 4,
                    "message": 5
                }
            },
        },
        {
            "label": "Clean - Clean the project",
            "type": "shell",
            "command": "${config:idf.pythonBinPath} ${config:idf.espIdfPath}/tools/idf.py fullclean",
            "windows": {
                "command": "${config:idf.pythonBinPathWin} ${config:idf.espIdfPathWin}\\tools\\idf.py fullclean"
            },
            "options": {
                "env": {
                    "PATH": "${config:idf.customExtraPaths}"
                }
            },
            "problemMatcher": [
                {
                    "owner": "cpp",
                    "fileLocation": ["relative", "${workspaceFolder}"],
                    "pattern": {
                        "regexp": "^\\.\\.(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
                        "file": 1,
                        "line": 2,
                        "column": 3,
                        "severity": 4,
                        "message": 5
                    }
                },
                {
                    "owner": "cpp",
                    "fileLocation": "absolute",
                    "pattern": {
                        "regexp": "^[^\\.](.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
                        "file": 1,
                        "line": 2,
                        "column": 3,
                        "severity": 4,
                        "message": 5
                    }
                }
            ],
        },
        {
            "label": "Flash - Flash the device",
            "type": "shell",
            "command": "${config:idf.pythonBinPath} ${config:idf.espIdfPath}/tools/idf.py -p ${config:idf.port} -b ${config:idf.baudRate} flash",
            "windows": {
                "command": "${config:idf.pythonBinPathWin} ${config:idf.espIdfPathWin}\\tools\\idf.py flash -p ${config:idf.portWin} -b ${config:idf.baudRate}"
            },
            "options": {
                "env": {
                    "PATH": "${config:idf.customExtraPaths}"
                }
            },
            "problemMatcher": [
                {
                    "owner": "cpp",
                    "fileLocation": ["relative", "${workspaceFolder}"],
                    "pattern": {
                        "regexp": "^\\.\\.(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
                        "file": 1,
                        "line": 2,
                        "column": 3,
                        "severity": 4,
                        "message": 5
                    }
                },
                {
                    "owner": "cpp",
                    "fileLocation": "absolute",
                    "pattern": {
                        "regexp": "^[^\\.](.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
                        "file": 1,
                        "line": 2,
                        "column": 3,
                        "severity": 4,
                        "message": 5
                    }
                }
            ],
        },
        {
            "label": "Monitor: Start the monitor",
            "type": "shell",
            "command": "${config:idf.pythonBinPath} ${config:idf.espIdfPath}/tools/idf.py -p ${config:idf.port} -b ${config:idf.baudRate} monitor",
            "windows": {
                "command": "${config:idf.pythonBinPathWin} ${config:idf.espIdfPathWin}\\tools\\idf.py monitor -p ${config:idf.portWin} -b ${config:idf.baudRate}"
            },
            "options": {
                "env": {
                    "PATH": "${config:idf.customExtraPaths}",
                }
            },
            "dependsOn": "Flash - Flash the device",
        },
        {
            "label":"OpenOCD: Start openOCD",
            "type":"shell",
            "presentation": {
                "echo": true,
                "reveal": "never",
                "focus": false,
                "panel":"new"
            },
            "command":"openocd -s ${command:espIdf.getOpenOcdScriptValue} ${command:espIdf.getOpenOcdConfigs}",
            "windows": {
                "command": "openocd.exe -s ${command:espIdf.getOpenOcdScriptValue} ${command:espIdf.getOpenOcdConfigs}"
            },
            "options": {
                "env": {
                    "PATH": "${config:idf.customExtraPaths}"
                }
            },
            "problemMatcher": {
                "owner": "cpp",
                "fileLocation": "absolute",
                "pattern": {
                    "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
                    "file": 1,
                    "line": 2,
                    "column": 3,
                    "severity": 4,
                    "message": 5
                }
            },
        },
        {
            "label": "adapter",
            "type": "shell",
            "command": "${config:idf.pythonBinPath}",
            "isBackground": true,
            "options": {
                "env": {
                    "PATH": "${config:idf.customExtraPaths}",
                    "PYTHONPATH": "${command:espIdf.getExtensionPath}/esp_debug_adapter/debug_adapter"
                }
            },
            "problemMatcher": {
                "background": {
                    "beginsPattern": "\bDEBUG_ADAPTER_STARTED\b",
                    "endsPattern": "DEBUG_ADAPTER_READY2CONNECT",
                    "activeOnStart": true
                },
                "pattern": {
                    "regexp": "(\\d+)-(\\d+)-(\\d+)\\s(\\d+):(\\d+):(\\d+),(\\d+)\\s-(.+)\\s(ERROR)",
                    "file": 8,
                    "line": 2,
                    "column": 3,
                    "severity": 4,
                    "message": 9
                }
            },
            "args": [
                "${command:espIdf.getExtensionPath}/esp_debug_adapter/debug_adapter_main.py",
                "-e", "${workspaceFolder}/build/${command:espIdf.getProjectName}.elf",
                "-s", "${command:espIdf.getOpenOcdScriptValue}",
                "-ip", "localhost",
                "-dn", "${config:idf.adapterTargetName}",
                "-om",
                "connect_to_instance"
            ],
            "windows": {
                "args": [
                    "${command:espIdf.getExtensionPath}/esp_debug_adapter/debug_adapter_main.py",
                    "-e", "${workspaceFolder}/build/${command:espIdf.getProjectName}.elf",
                    "-s", "${command:espIdf.getOpenOcdScriptValue}",
                    "-ip", "localhost",
                    "-dn", "${config:idf.adapterTargetName}",
                    "-om",
                    "connect_to_instance"
                ]
            }
        }
    ]
}
```

Global settings:
```
{
    "workbench.colorTheme": "Visual Studio Dark",
    "idf.espIdfPath": "/home/lab-pc-linux/esp-idf",
    "idf.toolsPath": "/home/lab-pc-linux/.espressif",
    "idf.customExtraPaths": "/home/lab-pc-linux/.espressif/python_env/idf4.0_py3.8_env/bin:/usr/bin:/home/lab-pc-linux/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32-elf/bin:/home/lab-pc-linux/.espressif/tools/esp32ulp-elf/2.28.51.20170517/esp32ulp-elf-binutils/bin:/home/lab-pc-linux/.espressif/tools/openocd-esp32/v0.10.0-esp32-20190313/openocd-esp32/bin",
    "idf.customExtraVars": "{\"OPENOCD_SCRIPTS\":\"/home/lab-pc-linux/.espressif/tools/openocd-esp32/v0.10.0-esp32-20190313/openocd-esp32/share/openocd/scripts\"}",
    "idf.pythonBinPath": "/home/lab-pc-linux/.espressif/python_env/idf4.0_py3.8_env/bin/python",
    "idf.openOcdConfigs": [
    
        "interface/ftdi/esp32_devkitj_v1.cfg",
        "board/esp-wroom-32.cfg"
    ],
    "C_Cpp.updateChannel": "Insiders"
}
```

My suspicion is that the ${command:espIdf.getExtensionPath} and such environment variables are not working right, however instead of being empty they seem to completely terminate the task without giving an error message.

**Environment (please complete the following information):**

- OS Name & Version: Ubuntu 20.04
- VSCode Version: 1.47.1
- ESP-IDF Version: 4.0.1
- Python Version: [e.g. 2.7.10]

### PR DESCRIPTION
**Pull request by brianignacio5**
`registerIDFCommand` was not returning the value from the callback function which make tasks.json and launch.json command executions (which expected a return value) fails.

Fix #141

### CODE REVIEW

File: src/extension.ts [hunk 1]
```diff
@@ -142,9 +142,10 @@ export async function activate(context: vscode.ExtensionContext) {
     const telemetryCallback = (...args: any[]) => {
```
Comment (pwmb) [inline src/extension.ts:142]: Lets change this  `(...args: any[]) => {` to `(...args: any[]): any => {` because by default it assumes return is `void`
