### PR TITLE
fix env path in windows and python on terminal (VSC-319)

### LINKED ISSUE #93: Error on build in version 0.2.1 (VSC-316)
**Describe the bug**
Build randomly fails with error: "Make sure you have the build tools installed and set in $PATH". 
After a restart it usually works, but not always. When it fails, there is no message in "ESP-IDF Build" output. The behavior is the same whether esp-idf is installed using the Windows installer or the wizard in the extension. 

Downgrading the extension to 0.2.0 solves the problem.

**To Reproduce**
1. Install ESP-IDF using Windows installer or using the wizard in the vscode-esp-idf extension.
1. Run either "ESP-IDF: Build your project" task or click the build button in status bar.

**Expected behavior**
Project gets build as ESP-IDF is installed and the extension is correctly configured.

**Environment (please complete the following information):**

- OS Name & Version: Windows 10 1909
- VSCode Version: 1.44.2
- ESP-IDF Version: 4.0.0
- Python Version: 3.8

**Logs**
```
{"user":true,"message":"Make sure you have the build tools installed and set in $PATH","stack":"Error: spawn cmake ENOENT\n\tat Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)\n\tat onErrorNT (internal/child_process.js:456:16)\n\tat processTicksAndRejections (internal/process/task_queues.js:77:11)","level":"error","timestamp":"2020-05-02T20:03:51.383Z"}
```

### PR DESCRIPTION
**Pull request by brianignacio5**
Closes #93, #100 

Normalize modifiedEnv PATH and Path updating. 

Also fix wrong python picked from ESP-IDF Terminal (should use the virtualenv)

### CODE REVIEW

**Comment by mitchjs** [comment]
seems like it fixed issue.... maybe merge into master asap and release v0.2.2

File: src/extension.ts [hunk 1]
```diff
@@ -1302,6 +1302,13 @@ function createIdfTerminal() {
     const envSetCmd =
       process.platform === "win32" ? `set "IDF_PATH=` : `export IDF_PATH="`;
     espIdfTerminal.sendText(`${envSetCmd}${modifiedEnv.IDF_PATH}"`);
+    const setPythonEnvCmd =
```
Comment (SoumeshBanerjee) [inline src/extension.ts:1305]: Is this used somewhere ?

Comment (brianignacio5) [reply src/extension.ts:1305]: For some reason, we need to override IDF_PATH and PATH using terminal export/set because it seems the terminal API is not overriding variables just post appending.

I just noticed there is an option to strictly use the env we pass to the terminal. Will update now.

File: src/utils.ts [hunk 2]
```diff
@@ -571,7 +561,26 @@ export function appendIdfAndToolsToPath() {
...
+    modifiedEnv.Path =
+      path.join(modifiedEnv.IDF_PATH, "tools") +
+      path.delimiter +
+      modifiedEnv.Path;
+    if (modifiedEnv.Path && !modifiedEnv.Path.includes(extraPaths)) {
+      modifiedEnv.Path = extraPaths + path.delimiter + modifiedEnv.Path;
+    }
+    modifiedEnv.Path = `${IDF_ADD_PATHS_EXTRAS}${path.delimiter}${modifiedEnv.Path}`;
+  } else {
+    modifiedEnv.PATH =
```
Comment (igrr) [inline src/utils.ts:575]: Sorry for a dumb question, but is it not possible to do something like
```
if (process.platform == "win32") {
  path_name = "Path";
} else {
  path_name = "PATH";
}
modifedEnv[path_name] = ...
```
to avoid duplicating the code?

File: src/espIdf/apptrace/tree/appTraceArchiveTreeDataProvider.ts [hunk 3]
```diff
@@ -51,7 +51,7 @@ export class AppTraceArchiveTreeDataProvider
     return this.appTraceArchives;
   }
   public refresh() {
-    this.OnDidChangeTreeData.fire();
+    this.OnDidChangeTreeData.fire(null);
```
[the remark this answers is not in the document]
Comment (brianignacio5) [reply src/espIdf/apptrace/tree/appTraceArchiveTreeDataProvider.ts:54]: Yes, the new vscode API requires an argument here.

Comment (pwmb) [inline src/espIdf/apptrace/tree/appTraceArchiveTreeDataProvider.ts:54]: @brianignacio5 I tried (latest changes) without passing `null` it compiles fine and run as expected.
What is the error you got here ?
