### PR TITLE
[VSC-1573] ensure build directories exist and resolve relative paths

### LINKED ISSUE #1430: ESP IDF extension ignore the sdkconfigFilePath in the esp_idf_project_configuration.json file
### OS

Linux

### Operating System version

Ubuntu 24.04

### Visual Studio Code version

1.97.2

### ESP-IDF version

5.4

### Python version

3.12

### Doctor command output

[report.txt](https://github.com/user-attachments/files/18828227/report.txt)

### Extension

[esp_idf_vsc_ext.log](https://github.com/user-attachments/files/18828233/esp_idf_vsc_ext.log)

### Description

Hello,
I'm trying to setup my project using the esp_idf_project_configuration.json, as i need to have multiple projects inside my working directory.
I'm setting the sdkconfigFilePath to tell to the ESP-IDF extension where to find the sdkconfig file for each configuration and everything is working fine for building. The issue comes when i try to flash. 
This is the command that is displayed during building: 

Image

If you look the sdkconfig path that is using is different from the one that i set: 

Image
(I also tried using absolute path but with no luck as explained in this other ticket: https://github.com/espressif/vscode-esp-idf-extension/issues/1408).

I'm using the Extension provided in this ticket: https://github.com/espressif/vscode-esp-idf-extension/issues/1425

### Debug Message

When building: 
Image
When flashing: 
Image

### Other Steps to Reproduce

_No response_

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [x] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

### PR DESCRIPTION
**Pull request by radurentea**
## Description

Fixed an issue where relative paths in project configurations were not being handled correctly and build directories were not being created automatically. The extension now properly resolves relative paths to absolute using the workspace folder as the base and ensures build directories exist before build commands are executed.

Also, when the esp_idf_project_configuration.json file is being updated, the configurations are updated in "real-time".

Variables also work:
${workspaceFolder}
${workspaceRoot}
${env:VARNAME}

Fixes https://github.com/espressif/vscode-esp-idf-extension/issues/1408
Fixes #1430
Fixes https://github.com/espressif/vscode-esp-idf-extension/issues/1493

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Steps to test this pull request

1) Create a project using example project **"multi_config"** in esp_idf_project_configuration.json use relative paths for **"buildDirectoryPath"** property

```json
{
  "prod1": {
    "build": {
      "compileArgs": [],
      "ninjaArgs": [],
      "buildDirectoryPath": "build.prod1",
      "sdkconfigDefaults": [
        "sdkconfig.prod_common",
        "sdkconfig.prod1"
      ],
      "sdkconfigFilePath": ""
    },
    "env": {},
    "flashBaudRate": "",
    "monitorBaudRate": "",
    "openOCD": {
      "debugLevel": 0,
      "configs": [],
      "args": []
    },
    "tasks": {
      "preBuild": "",
      "preFlash": "",
      "postBuild": "",
      "postFlash": ""
    }
  },
  "prod2": {
    "build": {
      "compileArgs": [],
      "ninjaArgs": [],
      "buildDirectoryPath": "${workspaceFolder}/build.prod2",
      "sdkconfigDefaults": [
        "sdkconfig.prod_common",
        "sdkconfig.prod2"
      ],
      "sdkconfigFilePath": ""
    },
    "env": {},
    "flashBaudRate": "",
    "monitorBaudRate": "",
    "openOCD": {
      "debugLevel": 0,
      "configs": [],
      "args": []
    },
    "tasks": {
      "preBuild": "",
      "preFlash": "",
      "postBuild": "",
      "postFlash": ""
    }
  }
}

```
2) Select either configuration from the ESP-IDF Project Configuration panel
3) Try to build the project

**Expected behaviour:**

- Build directories should be created automatically if they don't exist
- Build should succeed using the correct paths
- No errors about missing directories or invalid paths should occur

## How has this been tested?

As described above

**Test Configuration**:
* ESP-IDF Version: 5.4
* OS (Windows,Linux and macOS): Windows 11

## Checklist
- [ ] PR Self Reviewed
- [x] Applied Code formatting
- [ ] Added Documentation
- [ ] Added Unit Test
- [ ] Verified on all platforms - Windows,Linux and macOS

### CODE REVIEW

File: src/project-conf/index.ts [hunk 1]
```diff
@@ -58,32 +58,47 @@ export async function getProjectConfigurationElements(workspaceFolder: Uri) {
...
-        postBuild: projectConfJson[elem].tasks?.postBuild,
-        postFlash: projectConfJson[elem].tasks?.postFlash,
-      },
-    } as ProjectConfElement;
-  });
+  await Promise.all(
+    Object.keys(projectConfJson).map(async (elem) => {
+      const buildConfig = projectConfJson[elem].build;
+      const buildDirPath = buildConfig?.buildDirectoryPath
+        ? Uri.joinPath(workspaceFolder, buildConfig.buildDirectoryPath).fsPath
```
Comment (brianignacio5) [inline src/project-conf/index.ts:65]: Are all given paths relatives? What happens if the user defined a full path in `projectConfJson[elem].build.buildDirectoryPath`? 

I believe we should validate that the current value is a relative path. We could check that the current value with `await pathExists` before joining to the workspaceFolder.

File: src/project-conf/index.ts [hunk 2]
```diff
@@ -58,32 +58,47 @@ export async function getProjectConfigurationElements(workspaceFolder: Uri) {
...
+        await ensureDir(buildDirPath);
+      }
 
+      projectConfElements[elem] = {
+        build: {
+          compileArgs: buildConfig?.compileArgs,
+          ninjaArgs: buildConfig?.ninjaArgs,
+          buildDirectoryPath: buildDirPath,
+          sdkconfigDefaults: buildConfig?.sdkconfigDefaults?.map(
+            (path) => Uri.joinPath(workspaceFolder, path).fsPath
```
Comment (brianignacio5) [inline src/project-conf/index.ts:78]: Same here.

File: src/project-conf/index.ts [hunk 3]
```diff
@@ -58,32 +58,47 @@ export async function getProjectConfigurationElements(workspaceFolder: Uri) {
...
+          ),
+          sdkconfigFilePath: buildConfig?.sdkconfigFilePath
+            ? Uri.joinPath(workspaceFolder, buildConfig.sdkconfigFilePath)
```
Comment (brianignacio5) [inline src/project-conf/index.ts:81]: same here

**Review by brianignacio5 — CHANGES_REQUESTED** [review]
I suggest we validate that the given path string be validated to separate and support both relative and absolute paths.

File: src/project-conf/index.ts [hunk 4]
```diff
@@ -74,13 +85,14 @@ export async function getProjectConfigurationElements(workspaceFolder: Uri) {
...
           ninjaArgs: buildConfig?.ninjaArgs,
           buildDirectoryPath: buildDirPath,
-          sdkconfigDefaults: buildConfig?.sdkconfigDefaults?.map(
-            (path) => Uri.joinPath(workspaceFolder, path).fsPath
-          ),
-          sdkconfigFilePath: buildConfig?.sdkconfigFilePath
-            ? Uri.joinPath(workspaceFolder, buildConfig.sdkconfigFilePath)
-                .fsPath
-            : buildConfig?.sdkconfigFilePath,
+          sdkconfigDefaults: (await pathExists(buildConfig?.sdkconfigDefaults))
```
Comment (brianignacio5) [inline src/project-conf/index.ts:88]: Need to consider that sdkconfigDefaults is an array of files so this part of code would fail.

File: src/project-conf/index.ts [hunk 5]
```diff
@@ -99,3 +121,30 @@ export async function saveProjectConfFile(
...
+ * Handles both single path string or array of paths.
+ */
+async function resolveConfigPaths(
+  workspaceFolder: Uri,
+  paths?: string | string[]
+): Promise<string | string[]> {
+  if (!paths) return undefined;
+
+  if (Array.isArray(paths)) {
+    return Promise.all(
```
Comment (brianignacio5) [inline src/project-conf/index.ts:136]: Does this function needs to be asynchronous? I believe all inputs and functions used are synchronous.

**Review by brianignacio5 — CHANGES_REQUESTED** [review]

File: src/statusBar/index.ts [hunk 6]
```diff
@@ -101,16 +109,31 @@ export async function createCmdsStatusBarItems(workspaceFolder: Uri) {
...
-      `$(${
-        commandDictionary[CommandKeys.SelectProjectConfiguration].iconId
-      }) ${projectConf}`,
-      commandDictionary[CommandKeys.SelectProjectConfiguration].tooltip,
-      CommandKeys.SelectProjectConfiguration,
-      99,
-      commandDictionary[CommandKeys.SelectProjectConfiguration].checkboxState
-    );
+  if (projectConfExists) {
+    if (!projectConf) {
```
Comment (brianignacio5) [inline src/statusBar/index.ts:113]: `projectConf` doesn't mean is an error. Means the user has not selected a profile at the moment. Even if `ESP.ProjectConfiguration.PROJECT_CONFIGURATION_FILENAME` exists.

File: src/project-conf/index.ts [hunk 7]
```diff
@@ -58,32 +59,53 @@ export async function getProjectConfigurationElements(workspaceFolder: Uri) {
...
+      // Ensure directory is created for the resolved path
+      if (buildDirPath) {
+        await ensureDir(buildDirPath);
+      }
+      projectConfElements[elem] = {
+        build: {
+          compileArgs: buildConfig?.compileArgs,
+          ninjaArgs: buildConfig?.ninjaArgs,
+          buildDirectoryPath: buildDirPath,
+          sdkconfigDefaults: (await resolveConfigPaths(
```
Comment (brianignacio5) [inline src/project-conf/index.ts:83]: Await is not needed if  function is not asynchronous

**Review by brianignacio5 — CHANGES_REQUESTED** [review]

**Comment by brianignacio5** [comment]
Project Configuration Editor related bug:

When `esp_idf_project_configuration.json` is modified, the currently selected profile (which exists in vscode workspace state) is not updated. We need a file watcher for this file to see if it is modified and reload the selected profile. (vscode has file watcher api check sdkconfig file watcher in code, and extension command select current profile function to copy code for reload selected profile

File: src/project-conf/ProjectConfigurationManager.ts [hunk 8]
```diff
@@ -201,20 +203,35 @@ export class ProjectConfigurationManager {
...
+   * Sets the configuration status in the status bar
+   * @param isSelected Whether a configuration is selected
+   * @param isInvalid Whether the configuration is invalid
+   */
+  private setConfigurationStatus(isSelected: boolean, isInvalid: boolean): void {
+    let statusBarItemName: string;
+    let statusBarItemTooltip: string;
+    let commandToUse: string;
+
+    if (isInvalid) {
```
Comment (brianignacio5) [inline src/project-conf/ProjectConfigurationManager.ts:226]: I don't think this implementation is correct.

The status is either invalid, not selected or selected. These 3 states are easy to determine:

1) Selected: `currentSelectedConfig ` is defined and is a member of `currentVersions`. If currentSelectedConfig.name === currentVersions[someIndex].name but some fields are different, we should update currentSelectedConfig.

```ts
const configData = JSON.parse(utils.readFileSync(this.configFilePath));
const currentVersions = Object.keys(configData);
const currentSelectedConfig = ESP.ProjectConfiguration.store.get<string>(
        ESP.ProjectConfiguration.SELECTED_CONFIG
      );
```

2) Invalid: Current configFilePath doesn't exist or currentSelectedConfig.name !== currentVersions[someIndex].name. Means that current selected profile was deleted from configFilePath and a new profile needs to be selected.

3) No profile is selected. 


I think this function can be simplified by:

1) Check if currentSelectedConfig exists? If it doesn't set `No Configuration Selected` state.
2) If currentSelectedConfig exists and is valid set it in the status bar
3) If currentSelectedConfig exists but is invalid there is 2 cases:
a) If the profile was deleted, you can delete the profile from ESP.ProjectConfiguration.store and SELECTED_CONFIG
b) If the configFilePath doesn't exists then everything is invalid and you can delete the profile from ESP.ProjectConfiguration.store and SELECTED_CONFIG

**Review by brianignacio5 — CHANGES_REQUESTED** [review]
I believe the currently selected profile management can be simplified.

**Review by brianignacio5 — APPROVED** [review]
LGTM with minor change.

Why we need to ensure the build directory exists here ? Every time you open the Project Configuration editor now create the build directory for all the profiles.

**Review by Fabricio-ESP — APPROVED** [review]
Confirmed working, tested on Windows and MacOS environment.
Wildcards are preserved on project_configuration.json file.
No issues building sample project and toggling between different configurations
